app5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),
    path('admin/', admin.site.urls),
]

bases/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from bases.views import Home
urlpatterns = [

    path('',Home.as_view(),name='home'),
    path('login/',auth_views.LoginView.as_view(template_name='bases/login.html'),name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='bases/login.html'),name = 'logout'),
]

inv/urls.py
from django.urls import path
from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDel, SubCategoriaView,SubCategoriaNew,SubCategoriaEdit, \
    SubCategoriaDel

urlpatterns = [
    path('categorias/',CategoriaView.as_view(), name = 'categoria_list'),
    path('categorias/new',CategoriaNew.as_view(), name = 'categoria_new'),
    path('categorias/edit/<int:pk>',CategoriaEdit.as_view(), name = 'categoria_edit'),
    path('categorias/delete/<int:pk>',CategoriaDel.as_view(), name = 'categoria_del'),

    path('subcategorias/',SubCategoriaView.as_view(), name = 'subcategoria_list'),
    path('subcategorias/new', SubCategoriaNew.as_view(), name='subcategoria_new'),
    path('subcategorias/edit/<int:pk>', SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/delete/<int:pk>',SubCategoriaDel.as_view(), name = 'subcategoria_del'),
]

bases/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)
    uc = models.ForeignKey(User, on_delete= models.CASCADE)
    um = models.IntegerField(blank=True, null = True)

    class Meta:
        abstract = True

inv/models.py
from django.db import models
from bases.models import ClaseModelo
# Create your models here.
class Categoria(ClaseModelo):
    descripcion = models.CharField(max_length=100, help_text='Descripcion de la categoria', unique= True)

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name_plural = "Categorias"

class SubCategoria(ClaseModelo):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion =models.CharField(
        max_length=100,
        help_text='Descripcion de la Categoria'
    )
    def __str__(self):
        return '{}:{}'.format(self.categoria.descripcion, self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(SubCategoria, self).save()

    class Meta:
        verbose_name_plural = "Sub Categorias"
        unique_together = ('categoria','descripcion')

inv/forms.py
from django import forms
from .models import Categoria, SubCategoria

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['descripcion','estado']
        labels = {"descripcion":"Descripcion de la Categoria",
                  "estado":"Estado"}
        widgets = {'descripcion':forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class':'form-control'})

class SubCategoriaForm(forms.ModelForm):
    categoria = forms.ModelChoiceField(
        queryset=Categoria.objects.filter(estado=True)
        .order_by('descripcion')
    )
    class Meta:
        model = SubCategoria
        fields = ['categoria','descripcion','estado']
        labels = {"descripcion":"Sub Categoria",
                  "estado":"Estado"}
        widgets = {'descripcion':forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class':'form-control'})

        self.fields['categoria'].emply_label = "Seleccione Categoria"
                

bases/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

# Create your views here.
class Home(LoginRequiredMixin, generic.TemplateView):
    template_name = 'bases/home.html'
    login_url = 'bases:login'

inv/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Categoria, SubCategoria
from .forms import CategoriaForm, SubCategoriaForm
# Create your views here.
class CategoriaView(LoginRequiredMixin, generic.ListView):
    model = Categoria
    template_name = "inv/categoria_list.html"
    context_object_name = "obj"
    login_url = "bases:login"

class CategoriaNew(LoginRequiredMixin, generic.CreateView):
    model = Categoria
    template_name = "inv/categoria_form.html"
    context_object_name = "obj"
    form_class = CategoriaForm
    success_url = reverse_lazy("inv:categoria_list")
    login_url = "bases:login"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class CategoriaEdit(LoginRequiredMixin, generic.UpdateView):
    model = Categoria
    template_name = "inv/categoria_form.html"
    context_object_name = "obj"
    form_class = CategoriaForm
    success_url = reverse_lazy("inv:categoria_list")
    login_url = "bases:login"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class CategoriaDel(LoginRequiredMixin, generic.DeleteView):
    model = Categoria
    template_name = 'inv/catalogos_del.html'
    context_object_name = "obj"
    success_url = reverse_lazy("inv:categoria_list")

class SubCategoriaView(LoginRequiredMixin, generic.ListView):
    model = SubCategoria
    template_name = "inv/subcategoria_list.html"
    context_object_name = "obj"
    login_url = "bases:login"

class SubCategoriaNew(LoginRequiredMixin, generic.CreateView):
    model = SubCategoria
    template_name = "inv/subcategoria_form.html"
    context_object_name = "obj"
    form_class = SubCategoriaForm
    success_url = reverse_lazy("inv:subcategoria_list")
    login_url = "bases:login"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class SubCategoriaEdit(LoginRequiredMixin, generic.UpdateView):
    model = Categoria
    template_name = "inv/subcategoria_form.html"
    context_object_name = "obj"
    form_class = SubCategoriaForm
    success_url = reverse_lazy("inv:subcategoria_list")
    login_url = "bases:login"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class SubCategoriaDel(LoginRequiredMixin, generic.DeleteView):
    model = SubCategoria
    template_name = 'inv/catalogos_del.html'
    context_object_name = "obj"
    success_url = reverse_lazy("inv:subcategoria_list")

bases/templates/bases/home.html
{% extends 'base/base.html' %}

bases/templates/bases/login.html
{% extends 'base/base.html' %}

{% block side_bar %}{% endblock %}
{% block top_bar %}{% endblock %}
{% block page_content %}{% endblock %}
{% block footer %}{% endblock %}
{% block login %}
    <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                      <small class="text-danger">


                      </small>
                  </div>
                  <form class="user" method="POST">
                      {% csrf_token %}
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" id="id_username" name="username" aria-describedby="emailHelp" placeholder="Usuario">
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" id="id_password" name="password" placeholder="Password">
                    </div>
                    <div class="form-group">
                      <div class="custom-control custom-checkbox small">
                        <input type="checkbox" class="custom-control-input" id="customCheck">
                        <label class="custom-control-label" for="customCheck">Remember Me</label>
                      </div>
                    </div>
                      {# { form.as_p }#}
                      <button type="submit" class="btn btn-primary btn-user btn-block">Acceder</button>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>
{% endblock %}

inv/templates/inv/catalogos_del.html
{% extends 'base/base.html' %}
{% block page_content %}
    <form method="POST" class="form-inline">
        {% csrf_token %}
        <div class="col-xl-3 col-md-6 mb-4">
                  <div class="card border-left-danger shadow h-100 py-2">
                    <div class="card-body">
                      <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                          <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Eliminar {{ obj.descripcion }}?</div>
                          <button type="submit" class="btn btn-danger"><i class="far fa-question-circle"></i> Si, Eliminar</button>
                        <!--    <a href="{% url 'inv:categoria_list' %}" class="btn btn-success"><span class = "fa fa-undo"></span>Cancelar</a> -->
                          <a href="{{  }}" class="btn btn-success"><span class = "fa fa-undo"></span>Cancelar</a> -->
                        </div>
                        <div class="col-auto">
                          <i class="far fa-question-circle fa-2x text-gray-300"></i>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
    </form>
{% endblock %}
{% block js_page %}
{% endblock %}

inv/templates/inv/categoria_form.html
{% extends 'base/base.html' %}

{% block page_content %}
    <form method = "POST" class = "form-inline">
    {% csrf_token %}
     <div class="col-xl-6 col-md-6 mb-4">
         {% if obj %}
         <div class="card border-left-warning shadow h-100 py-2">
             {% else %}
              <div class="card border-left-succes shadow h-100 py-2">
                {% endif %}
                  <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                         {% if obj %} Edit {% else %} Nueva {% endif %} Categoria
                      </div>
                        <div class = "dropdown-divider"></div>
                        <div class = "row">
                            <div class= "col-10">
                                    <div class="input-group">
                                        <input type="text" name="descripcion" maxlength="100" class="form-control" required id = "id_descripcion" placeholder="Descripcion"
                                               value="{% if obj %} {{ obj.descripcion }} {% endif %}">
                                    </div>
                                </div>
                                <div class="col-2">
                                    <div class = "form-group">
                                        <label for = "id_estado">Estado</label>
                                        <input type="checkbox" name="estado" class="form-control" id = "id_estado"
                                         {% if obj.estado %}  checked {% endif %}>
                                    </div>
                                </div>
                          <!--  -->

                        </div>
                        <!--         --------                 -->
                        <div class="dropdown-divider"></div>
                        <div class = "row">
                            <div class = "col">
                                <button type="submit" class="btn btn-danger"><span class = "fa fa-save"></span>Guardar</button>
                                <a href="{% url 'inv:categoria_list' %}" class="btn btn-success"><span class = "fa fa-undo"></span>Cancelar</a>
                            </div>
                        </div>


                    </div>

                  </div>
                </div>
              </div>
     </div>
    </form>
{% endblock %}
{% block js_page %}
{% endblock %}

inv/templates/inv/categoria_list.html
{% extends 'base/base.html' %}

{% block page_content %}
     <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Listado de Categorias</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Acciones </div>
                      <a class="dropdown-item" href="{% url 'inv:categoria_new' %}"><i class="far fa-calendar-plus"></i>Nueva</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    {% if not obj %}
                        <div class="alert alert-info">No hay Categorias</div>
                        {% else %}
                    <table class ="table table-striped table-hover">
                        <thead>
                            <th>Id</th>
                            <th>Descripcion</th>
                            <th>Estado</th>
                            <th>F. Creado</th>
                            <th>F. Modificado</th>
                            <th class="all">Acciones</th>
                        </thead>
                        <tbody>
                            {% for item in obj %}
                                <tr>
                                    <th>{{ item.id }}</th>
                                    <th>{{ item.description }}</th>
                                    <th>{{ item.estado|yesno:"Activo,Inactivo" }}</th>
                                    <th>{{ item.fc|date:"d/m/Y H:i:s"}}</th>
                                    <th>{{ item.fm|date:"d/m/Y H:i:s"}}</th>
                                    <td>
                                        <a href="{% url 'inv:categoria_edit' item.id %}" class="btn btn-warning btn-circle" role="button"></a><i class="far fa-edit"></i></a>
                                       <!--  <a href="" class="btn btn-warning btn-circle" role="button"></a><i class="far fa-edit"></i></a> -->
                                       <a href="{% url 'inv:categoria_del' item.id %}" class="btn btn-danger btn-circle" role="button"></a><i class="far fa-trash-alt"></i></a>
                                    </td>

                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                     {% endif %}
                </div>
              </div>
{% endblock %}
{% block js_page %}
    <script>
        $(document).ready(function () {
            $('.table').DataTable();
        });
    </script>
{% endblock %}

inv/templates/inv/subcategoria_form.html
{% extends 'base/base.html' %}

{% block page_content %}
    <form method = "POST" class = "form-inline">
    {% csrf_token %}
     <div class="col-xl-12 col-md-12 mb-12">
         {% if obj %}
         <div class="card border-left-warning shadow h-100 py-2">
             {% else %}
              <div class="card border-left-succes shadow h-100 py-2">
                {% endif %}
                  <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                         {% if obj %} Edit {% else %} Nueva {% endif %} Sub Categoria
                      </div>
                        <div class = "dropdown-divider"></div>
                        <div class = "row">
                            <div class= "col-5">
                                    <div class="input-group">
                                   <!--     <input type="text" name="descripcion" maxlength="100" class="form-control" required id = "id_descripcion" placeholder="Descripcion"
                                               value="{% if obj %} {{ obj.descripcion }} {% endif %}"> -->
                                            {{ form.categoria }}
                                    </div>
                                </div>
                            <div class= "col-5">
                                    <div class="input-group">
                                   <!--     <input type="text" name="descripcion" maxlength="100" class="form-control" required id = "id_descripcion" placeholder="Descripcion"
                                               value="{% if obj %} {{ obj.descripcion }} {% endif %}"> -->
                                    {{ form.descripcion }}
                                    </div>
                                </div>
                                <div class="col-2">
                                    <div class = "input-group">
                                     <!--   <label for = "id_estado">Estado</label>
                                        <input type="checkbox" name="estado" class="form-control" id = "id_estado"
                                         {% if obj.estado %}  checked {% endif %}> -->
                                        {{ form.estado }}
                                    </div>
                                </div>
                          <!--  -->

                        </div>
                        <!--         --------                 -->
                        <div class="dropdown-divider"></div>
                        <div class = "row">
                            <div class = "col">
                                <button type="submit" class="btn btn-danger"><span class = "fa fa-save"></span>Guardar</button>
                                <a href="{% url 'inv:subcategoria_list' %}" class="btn btn-success"><span class = "fa fa-undo"></span>Cancelar</a>
                            </div>
                        </div>


                    </div>

                  </div>
                </div>
              </div>
     </div>
    </form>
{% endblock %}
{% block js_page %}
{% endblock %}

inv/templates/inv/subcategoria_list.html
{% extends 'base/base.html' %}

{% block page_content %}
     <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Listado de Sub Categorias</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Acciones </div>
                      <a class="dropdown-item" href="{% url 'inv:subcategoria_new' %}"><i class="far fa-calendar-plus"></i>Nueva</a>

                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    {% if not obj %}
                        <div class="alert alert-info">No hay Sub Categorias</div>
                        {% else %}
                    <table class ="table table-striped table-hover">
                        <thead>
                            <th>Descripcion</th>
                            <th>Id</th>
                            <th>Descripcion</th>
                            <th>Estado</th>
                            <th>F. Creado</th>
                            <th>F. Modificado</th>
                            <th class="all">Acciones</th>
                        </thead>
                        <tbody>
                            {% for item in obj %}
                                <tr>
                                    <th>{{ item.categoria }}</th>
                                    <th>{{ item.id }}</th>
                                    <th>{{ item.description }}</th>
                                    <th>{{ item.estado|yesno:"Activo,Inactivo" }}</th>
                                    <th>{{ item.fc|date:"d/m/Y H:i:s"}}</th>
                                    <th>{{ item.fm|date:"d/m/Y H:i:s"}}</th>
                                    <td>
                                        <a href="{% url 'inv:subcategoria_edit' item.id %}" class="btn btn-warning btn-circle" role="button"></a><i class="far fa-edit"></i></a>
                                       <!--  <a href="" class="btn btn-warning btn-circle" role="button"></a><i class="far fa-edit"></i></a> -->
                                       <a href="{% url 'inv:categoria_del' item.id %}" class="btn btn-danger btn-circle" role="button"></a><i class="far fa-trash-alt"></i></a>
                                    </td>

                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                     {% endif %}
                </div>
              </div>
{% endblock %}
{% block js_page %}
    <script>
        $(document).ready(function () {
            $('.table').DataTable();
        });
    </script>
{% endblock %}